[[getting-started-tram-sagas]]
== Eventuate Tram Sagas

The Eventuate Tram Saga framework is a saga orchestration framework for Java microservices that use JDBC/JPA.
A saga is a mechanism for maintaining data consistency across multiple services in microservice architecture without using distributed transactions.
A http://microservices.io/patterns/data/saga.html[saga] consists of a series of a local transactions.

There are two different ways of coordinating a saga:

* choreography - the saga's participants exchange events
* orchestration - a centralized orchestrator uses request/asynchronous reply-style messaging to tell the participants what to do

Choreography works well for simple sagas but for more complex sagas, orchestration is often easier to understand.

Eventuate Tram Saga is described in more detail in my book https://www.manning.com/books/microservice-patterns[Microservice Patterns].
It is built on the https://github.com/eventuate-tram/eventuate-tram-core[Eventuate Tram framework], which enables an application to atomically update a database and publish a message without using JTA.

=== Learn more

To learn more:

* Read this https://microservices.io/patterns/data/saga.html[article]
* See this https://www.slideshare.net/chris.e.richardson/yow2018-events-and-commands-developing-asynchronous-microservices[presentation]
* The https://www.manning.com/books/microservices-patterns[Microservices Patterns book]

=== JavaDocs

* See the https://eventuate.io/docs/javadoc/eventuate-tram-sagas/eventuate-tram-sagas.html[Eventuate Tram Sagas JavaDocs]

=== Example applications:

* https://github.com/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders[Customers and Orders]
* https://github.com/microservice-patterns/ftgo-application[FTGO Example application for Microservice Patterns book]

=== Using Eventuate Tram Saga

There are four parts to using Eventuate Tram Saga to implement an orchestration-based saga:

. Specifying Maven/Gradle dependencies
. Writing the saga orchestrator
. Writing each saga participant
. Running the Eventuate Tram CDC service

==== Maven/Gradle artifacts

The artifacts are in https://bintray.com/eventuateio-oss/eventuate-maven-rc/eventuate-tram-sagas[Eventuate Maven Release Candidate Repository].
The latest version is:

image::https://api.bintray.com/packages/eventuateio-oss/eventuate-maven-rc/eventuate-tram-sagas/images/download.svg[link="https://bintray.com/eventuateio-oss/eventuate-maven-rc/eventuate-tram-sagas/_latestVersion"][link="https://bintray.com/eventuateio-oss/eventuate-maven-release/eventuate-tram-sagas/_latestVersion"]

In `gradle.properties`:

----
eventuateTramSagasVersion=LATEST_VERSION
----

In `build.gradle`, specify these maven repositories:

[source, groovy]
----
repositories {
    mavenCentral()
    jcenter()
}
----

===== Saga orchestrator dependencies

If you are writing a Saga orchestrator add this dependency to your project:

Spring:

[source, groovy]
----
dependency {

  compile "io.eventuate.tram.sagas:eventuate-tram-sagas-spring-orchestration-simple-dsl:$eventuateTramSagasVersion"

}
----

Micronaut:

[source, groovy]
----
dependency {

  compile "io.eventuate.tram.sagas:eventuate-tram-sagas-micronaut-orchestration-simple-dsl:$eventuateTramSagasVersion"

}
----

===== Saga participant dependencies

If you are writing a saga participant then add this dependency:

Spring:

[source, groovy]
----
dependency {

  compile "io.eventuate.tram.sagas:eventuate-tram-sagas-spring-participant:$eventuateTramSagasVersion"

}
----

Micronaut:

[source, groovy]
----
dependency {

  compile "io.eventuate.tram.sagas:eventuate-tram-sagas-micronaut-participant:$eventuateTramSagasVersion"

}
----

===== Eventuate Tram dependencies

You must also include one of the https://github.com/eventuate-tram/eventuate-tram-core[Eventuate Tram] 'implementation' artifacts:

[source, groovy]
----
dependencies {

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-producer-jdbc:$eventuateTramVersion"
  compile "io.eventuate.tram.core:eventuate-tram-<framework>-consumer-<message-broker>:$eventuateTramVersion"

  // In-memory JDBC database and in-memory messaging for testing
  testCompile `io.eventuate.tram.core:eventuate-tram-<framework>-in-memory:$eventuateTramVersion`

  // Saga orchestrator only

  testCompile "io.eventuate.tram.sagas:eventuate-tram-sagas-spring-testing-support:$eventuateTramSagasVersion"

}
----

where

* `framework` is `spring` or `micronaut`
* `message-broker` is `kafka`, `apachemq`, `rabbitmq` or `redis`.

Note: `micronaut` only supports `kafka`

=== Eventuate Bom

It is not necessary to specify artifact versions if use eventuate bom, it will resolve them automatically:

[source, groovy]
----
dependencies {
    implementation(platform("io.eventuate.platform:platform-dependencies:$eventuateBomVersion"))
}
----

then version can be avoided:

----
dependencies {
  compile "io.eventuate.tram.sagas:eventuate-tram-sagas-micronaut-participant"
}
----

==== Writing an orchestrator

The https://github.com/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders[Customers and Orders (Spring)] uses a saga to create an `Order` in the `Order Service` and reserve credit in the `Customer Service`.
The `CreateOrderSaga` consists of the following three steps:

1. The `CreateOrderSaga` is instantiated after the `Order` is created.
Consequently, the first step is simply a compensating transaction, which is executed in the credit cannot be reserved to reject the order.
2. Requests the `CustomerService` to reserve credit for the order.
If the reservation is success, the next step is executed.
Otherwise, the compensating transactions are executed to roll back the saga.
3. Approves the order, if the credit is reserved.

https://github.com/eventuate-tram-examples/eventuate-tram-sagas-micronaut-examples-customers-and-orders[Micronaut version of Customers and Orders]

===== Writing the saga orchestrator class

Here is part of the definition of `CreateOrderSaga`.

[source, java]
----
public class CreateOrderSaga implements SimpleSaga<CreateOrderSagaData> {

  private SagaDefinition<CreateOrderSagaData> sagaDefinition =
          step()
            .withCompensation(this::reject)
          .step()
            .invokeParticipant(this::reserveCredit)
          .step()
            .invokeParticipant(this::approve)
          .build();


  @Override
  public SagaDefinition<CreateOrderSagaData> getSagaDefinition() {
    return this.sagaDefinition;
  }


  private CommandWithDestination reserveCredit(CreateOrderSagaData data) {
    long orderId = data.getOrderId();
    Long customerId = data.getOrderDetails().getCustomerId();
    Money orderTotal = data.getOrderDetails().getOrderTotal();
    return send(new ReserveCreditCommand(customerId, orderId, orderTotal))
            .to("customerService")
            .build();

...
----

The `reserveCredit()` creates a message to send to the `Customer Service` to reserve credit.

===== Configuring the application context for a saga orchestrator

====== Spring

[source,java]
----
@Configuration
...
@Import({SagaOrchestratorConfiguration.class,
...
TramMessageProducerJdbcConfiguration.class,
EventuateTramKafkaMessageConsumerConfiguration.class
})
public class OrderConfiguration {
...
----

====== Micronaut

TBD


===== Creating an saga orchestrator

The `OrderService` creates the saga using `SagaInstanceFactory`:

====== Spring

[source, java]
----
public class OrderService {

  @Autowired
  private SagaInstanceFactory sagaInstanceFactory;

  @Autowired
  private OrderRepository orderRepository;

  @Transactional
  public Order createOrder(OrderDetails orderDetails) {
    ResultWithEvents<Order> oe = Order.createOrder(orderDetails);
    Order order = oe.result;
    orderRepository.save(order);
    CreateOrderSagaData data = new CreateOrderSagaData(order.getId(), orderDetails);

    sagaInstanceFactory.create(createOrderSaga, data);

    return order;
  }

}
----

====== Micronaut

[source, java]
----
public class OrderService {

  @Inject
  private SagaInstanceFactory sagaInstanceFactory;

  @PersistenceContext
  private EntityManager entityManager;

  @Transactional
  public Order createOrder(OrderDetails orderDetails) {
    CreateOrderSagaData data = new CreateOrderSagaData(orderDetails);
    sagaInstanceFactory.create(createOrderSaga, data);
    return entityManager.find(Order.class, data.getOrderId());
  }

}
----

==== Writing a saga participant

Here is the  `CustomerCommandHandler`, which handles the command to reserve credit:

===== Spring

[source, java]
----
public class CustomerCommandHandler {

  @Autowired
  private CustomerRepository customerRepository;

  public CommandHandlers commandHandlerDefinitions() {
    return SagaCommandHandlersBuilder
            .fromChannel("customerService")
            .onMessage(ReserveCreditCommand.class, this::reserveCredit)
            .build();
  }

  public Message reserveCredit(CommandMessage<ReserveCreditCommand> cm) {
     ...
  }
  ...
----

===== Micronaut

[source, java]
----
public class CustomerCommandHandler {

  @PersistenceContext
  private EntityManager entityManager;

  public CommandHandlers commandHandlerDefinitions() {
    return SagaCommandHandlersBuilder
            .fromChannel("customerService")
            .onMessage(ReserveCreditCommand.class, this::reserveCredit)
            .build();
  }

  public Message reserveCredit(CommandMessage<ReserveCreditCommand> cm) {
     ...
  }

}
  ...
----

==== Configuring the application context for a saga participant

===== Spring

[source, java]
----
@Configuration
@Import({
  SagaParticipantConfiguration.class,
  ...
  TramMessageProducerJdbcConfiguration.class,
  EventuateTramKafkaMessageConsumerConfiguration.class
})
...
@EnableAutoConfiguration
public class CustomerConfiguration {
  ....
----

===== Micronaut

TBD

==== Running the CDC service

In addition to a database and message broker, you will need to run the Eventuate Tram CDC service.
It reads messages and events inserted into the database and publishes them to Apache Kafka.
It is written using Spring Boot.
The easiest way to run this service during development is to use Docker Compose.
The https://github.com/eventuate-tram/eventuate-tram-core-examples-basic[Eventuate Tram Code Basic examples] project has an example https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/docker-compose-mysql-binlog.yml[docker-compose.yml file].
