= Eventuate Tram Saga

image::https://api.bintray.com/packages/eventuateio-oss/eventuate-maven-release/eventuate-tram-sagas/images/download.svg[link="https://bintray.com/eventuateio-oss/eventuate-maven-release/eventuate-tram-sagas/_latestVersion"]

The Eventuate Tram Saga framework is a saga orchestration framework for Java microservices that use JDBC/JPA.
A saga is a mechanism for maintaining data consistency across multiple services in microservice architecture without using distributed transactions.
A http://microservices.io/patterns/data/saga.html[saga] consists of a series of a local transactions.

There are two different ways of coordinating a saga:

* choreography - the saga's participants exchange events
* orchestration - a centralized orchestrator uses request/asynchronous reply-style messaging to tell the participants what to do

Choreography works well for simple sagas but for more complex sagas, orchestration is often easier to understand.

Eventuate Tram Saga is a framework for writing orchestration-based sagas.
It is described in more detail in my book https://www.manning.com/books/microservice-patterns[Microservice Patterns].
It is built on the https://github.com/eventuate-tram/eventuate-tram-core[Eventuate Tram framework], which enables an application to atomically update a database and publish a message without using JTA.

== Learn more

Recent presentations:

* QCONSF 2017 - http://microservices.io/microservices/news/2017/12/04/qconsf2017-presentation.html[slides]
* JavaOne 2017 - https://www.slideshare.net/chris.e.richardson/javaone2017-acid-is-so-yesterday-maintaining-data-consistency-with-sagas[slides] and https://www.youtube.com/watch?v=6P6dvNyvtps[video]

Example applications:

* https://github.com/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders[Customers and Orders]
* https://github.com/microservice-patterns/ftgo-application[FTGO Example application for Microservice Patterns book]

== Using Eventuate Tram Saga

There are four parts to using Eventuate Tram Saga to implement an orchestration-based saga:

. Specifying Maven/Gradle dependencies
. Writing the saga orchestrator
. Writing each saga participant
. Running the Eventuate Tram CDC service

=== Maven/Gradle artifacts

The artifacts are in https://bintray.com/eventuateio-oss/eventuate-maven-release/eventuate-tram-sagas[JCenter].
The latest version is:

image::https://api.bintray.com/packages/eventuateio-oss/eventuate-maven-release/eventuate-tram-sagas/images/download.svg[link="https://bintray.com/eventuateio-oss/eventuate-maven-release/eventuate-tram-sagas/_latestVersion"]

If you are writing a Saga orchestrator add this dependency to your project:

* `io.eventuate.tram.sagas:eventuate-tram-sagas-simple-dsl:$eventuateTramSagasVersion`

If you are writing a saga participant then add this dependency:

* `io.eventuate.tram.sagas:eventuate-jpa-sagas-framework:$eventuateTramSagasVersion`

You must also include one of the https://github.com/eventuate-tram/eventuate-tram-core[Eventuate Tram] 'implementation' artifacts:

* `io.eventuate.tram.core:eventuate-tram-jdbc-kafka:$eventuateTramVersion` - JDBC database and Apache Kafka message broker
* `io.eventuate.tram.core:eventuate-tram-in-memory:$eventuateTramVersion` - In-memory JDBC database and in-memory messaging for testing

=== Writing an orchestrator

The https://github.com/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders[Customers and Orders] uses a saga to create an `Order` in the `Order Service` and reserve credit in the `Customer Service`.
The `CreateOrderSaga` consists of the following three steps:

1. The `CreateOrderSaga` is instantiated after the `Order` is created.
Consequently, the first step is simply a compensating transaction, which is executed in the credit cannot be reserved to reject the order.
2. Requests the `CustomerService` to reserve credit for the order.
If the reservation is success, the next step is executed.
Otherwise, the compensating transactions are executed to roll back the saga.
3. Approves the order, if the credit is reserved.

==== Writing the saga orchestrator class

Here is part of the definition of `CreateOrderSaga`.

```java
public class CreateOrderSaga implements SimpleSaga<CreateOrderSagaData> {

  private SagaDefinition<CreateOrderSagaData> sagaDefinition =
          step()
            .withCompensation(this::reject)
          .step()
            .invokeParticipant(this::reserveCredit)
          .step()
            .invokeParticipant(this::approve)
          .build();


  @Override
  public SagaDefinition<CreateOrderSagaData> getSagaDefinition() {
    return this.sagaDefinition;
  }


  private CommandWithDestination reserveCredit(CreateOrderSagaData data) {
    long orderId = data.getOrderId();
    Long customerId = data.getOrderDetails().getCustomerId();
    Money orderTotal = data.getOrderDetails().getOrderTotal();
    return send(new ReserveCreditCommand(customerId, orderId, orderTotal))
            .to("customerService")
            .build();

...
```

The `reserveCredit()` creates a message to send to the `Customer Service` to reserve credit.

==== Creating an saga orchestrator

The `OrderService` creates the saga:

```java
public class OrderService {

  @Autowired
  private SagaManager<CreateOrderSagaData> createOrderSagaManager;

  @Autowired
  private OrderRepository orderRepository;

  @Transactional
  public Order createOrder(OrderDetails orderDetails) {
    ResultWithEvents<Order> oe = Order.createOrder(orderDetails);
    Order order = oe.result;
    orderRepository.save(order);
    CreateOrderSagaData data = new CreateOrderSagaData(order.getId(), orderDetails);
    createOrderSagaManager.create(data, Order.class, order.getId());
    return order;
  }

}
```

=== Writing a saga participant

Here is the  `CustomerCommandHandler`, which handles the command to reserve credit:

```java
public class CustomerCommandHandler {

  @Autowired
  private CustomerRepository customerRepository;

  public CommandHandlers commandHandlerDefinitions() {
    return SagaCommandHandlersBuilder
            .fromChannel("customerService")
            .onMessage(ReserveCreditCommand.class, this::reserveCredit)
            .build();
  }

  public Message reserveCredit(CommandMessage<ReserveCreditCommand> cm) {
     ...
  }
  ...
```


=== Running the CDC service

In addition to a database and message broker, you will need to run the Eventuate Tram CDC service.
It reads messages and events inserted into the database and publishes them to Apache Kafka.
It is written using Spring Boot.
The easiest way to run this service during development is to use Docker Compose.
The https://github.com/eventuate-tram/eventuate-tram-core-examples-basic[Eventuate Tram Code Basic examples] project has an example https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/docker-compose.yml[docker-compose.yml file].
