[[getting-started]]
== Getting started with Eventuate Tram


Learn how to get started with https://github.com/eventuate-tram/eventuate-tram-core[Eventuate Tram], a framework for transactional messaging.
Eventuate Tram sends and receives messages as part of a database transaction ensuring that your application atomically updates the database and publishes messages.
Currently, it supports the following databases:

* Transaction log tailing: MySQL, Postgres
* Polling: Other SQL databases

And, the following message brokers:

* Apache Kafka
* ActiveMQ
* RabbitMQ
* Redis

=== See also

* link:./about-eventuate-tram.html[Overview of EventuateTram]
* https://eventuate.io/exampleapps.html[Tram example applications]
* The https://github.com/eventuate-tram/eventuate-tram-core[Eventuate Tram Github repository]
* The https://github.com/eventuate-tram/eventuate-tram-sagas[Eventuate Tram Sagas Github repository]
* The https://www.manning.com/books/microservices-patterns[Microservices Patterns] book

=== JavaDocs

* See the https://eventuate.io/docs/javadoc/eventuate-tram/eventuate-tram.html[Eventuate Tram JavaDocs].

=== Project setup

Latest library version:

image::https://api.bintray.com/packages/eventuateio-oss/eventuate-maven-rc/eventuate-tram/images/download.svg[link="https://bintray.com/eventuateio-oss/eventuate-maven-rc/eventuate-tram/_latestVersion"]

==== Gradle


In `gradle.properties`:

```
eventuateTramVersion=LATEST_VERSION
```

In `build.gradle`, specify these maven repositories:


```groovy
repositories {
    mavenCentral()
    jcenter()
}
```

Include one or more of the following dependencies, depending on which API and implementation you want to use.

===== API artifacts

```groovy
dependencies {

  // Basic messaging

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-messaging:$eventuateTramVersion"

  // Domain events

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-events:$eventuateTramVersion"

  // Command/Async Reply messaging

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-commands:$eventuateTramVersion"
```

where

* `framework` is `spring` or `micronaut`

===== Producer implementation artifact

If your service is a producer, you must add this dependency:

```groovy
dependencies {

  // Producer implementation

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-producer-jdbc:$eventuateTramVersion"

}
```

===== Consumer implementation artifacts

If your service is a consumer, you must add a message broker-specific dependency:

```groovy
dependencies {

  // Consumer implementation

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-consumer-<message-broker>:$eventuateTramVersion"

}
```

where

* `framework` is `spring` or `micronaut`
* `message-broker` is `kafka`, `apachemq`, `rabbitmq` or `redis`.

Note: `micronaut` only supports `kafka`

If you want to use JDBC-based idempotency (see below) also include this dependency:

```groovy
dependencies {

  // Consumer idempotency

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-consumer-jdbc:$eventuateTramVersion"

}
```

where

* `framework` is `spring` or `micronaut`

See below for more details.

===== All-in-one artifacts

If you need all of the above artifacts, then you can include this one dependency:

```groovy
dependencies {

  // Consumer/Producer all-in-one

  compile "io.eventuate.tram.core:eventuate-tram-<framework>-jdbc-<message-broker>:$eventuateTramVersion"

}
```

where

* `framework` is `spring` or `micronaut`
* `message-broker` is `kafka`, `apachemq`, `rabbitmq` or `redis`.

Note: `micronaut` only supports `kafka`


=== Transactional messages

Eventuate Tram has APIs for sending and receiving messages as part of a database transaction.

==== Sending messages

Send a message using `MessageProducer`:

===== Spring

[source,java]
----
public abstract class AbstractTramMessageTest {

  @Autowired
  private MessageProducer messageProducer;

  @Test
  public void shouldReceiveMessage() {
    ...
    messageProducer.send(destination, MessageBuilder.withPayload(payload).build());
    ...
  }
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/messages/AbstractTramMessageTest.java[sending messages].

===== Micronaut

[source,java]
----
public abstract class AbstractTramMessageTest {

  @Inject
  private MessageProducer messageProducer;

  @Test
  public void shouldReceiveMessage() {
    ...
    messageProducer.send(destination, MessageBuilder.withPayload(payload).build());
    ...
  }
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/messages/AbstractTramMessageTest.java[sending messages].

==== Consuming messages

Receive messages using `MessageConsumer`:

===== Spring

[source,java]
----
public abstract class AbstractTramMessageTest {

  @Autowired
  private MessageConsumer messageConsumer;

  @Test
  public void shouldReceiveMessage() throws InterruptedException {
    messageConsumer.subscribe(subscriberId, Collections.singleton(destination), this::handleMessage);
    ...
  }

  private void handleMessage(Message message) {
    ...
  }
}
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/messages/AbstractTramMessageTest.java[consuming messages].

===== Micronaut

[source,java]
----
public abstract class AbstractTramMessageTest {

  @Inject
  private MessageConsumer messageConsumer;

  @Test
  public void shouldReceiveMessage() throws InterruptedException {
    messageConsumer.subscribe(subscriberId, Collections.singleton(destination), this::handleMessage);
    ...
  }

  private void handleMessage(Message message) {
    ...
  }
}
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/messages/AbstractTramMessageTest.java[sending messages].

==== Message interceptors

Eventuate Tram implements message interceptors.
Your service can define one or more message interceptors to inject custom logic into the various message processing steps.
It could, for example, add custom headers to a message.

A message interceptor must implement the `MessageInterceptor` interface.

```java
public interface MessageInterceptor {

  default void preSend(Message message) {}
  default void postSend(Message message, Exception e) {}

  default void preReceive(Message message) {}
  default void preHandle(String subscriberId, Message message) {}
  default void postHandle(String subscriberId, Message message, Throwable throwable) {}
  default void postReceive(Message message) {}

}
```

==== Message handler decorators

Eventuate Tram implements message handler decorators.
They are equivalent to Servlet Filters and are invoked when handling a message.
Eventuate Tram uses them to implement message consumer mechanisms such as idempotency and optimistic locking.
Your service can also define custom decorators.

`MessageHandlerDecorator` is the interface that message handler decorators must implement:

```
public interface MessageHandlerDecorator
     extends BiConsumer<SubscriberIdAndMessage, MessageHandlerDecoratorChain> {
  int getOrder();
}
```

The `@MessageHandlerDecorator``'s in the `ApplicationContext` are executed in the order defined by `getOrder()`.

==== Idempotent message consumers

A message broker might deliver the same message more than once.
A message consumer must typically be https://microservices.io/patterns/communication-style/idempotent-consumer.html[idempotent].
Some message consumers are naturally idempotent, e.g. `account.balance = event.newBalance`, and can be invoked repeatedly without error.
But others are not - e.g. `account.balance += event.amount` - and must be made idempotent by tracking the messages that they have consumed.

Eventuate Tram has an pluggable duplicate message detection mechanism.
`DuplicateMessageDetector` is the strategy interface.
There are the following concrete implementations:

* `SqlTableBasedDuplicateMessageDetector` - tracks successfully processed message IDs in a `RECEIVED_MESSAGES` tables.
Your message handling logic is executed within a transaction managed by this class.
* `NoopDuplicateMessageDetector` - does nothing.
Use this implementation when your message handlers are idempotent.
For example, the https://github.com/microservices-patterns/ftgo-application/blob/9f85c7744bfa2d58a2a9aefbb3b9eb43428df3ec/ftgo-order-history-service/src/main/java/net/chrisrichardson/ftgo/cqrs/orderhistory/messaging/OrderHistoryServiceMessagingConfiguration.java#L15[`Order History Service`] in the FTGO application tracks message IDs in a Dynamodb table
* `TransactionalNoopDuplicateMessageDetector` - it doesn't track message IDs but it does manage transactions.

.A note about transaction management
****
If you use a `DuplicateMessageDetector` that manages transactions then you must not manage transactions (e.g. use `@Transactional`) in your message handlers.
****

Your service's `ApplicationContext` must define an `DuplicateMessageDetector` `@Bean`.

===== Spring

[cols="4*a"]
|===

|
| `SqlTableBasedDuplicateMessageDetector`
| `TransactionalNoopDuplicateMessageDetector`
| `NoopDuplicateMessageDetector`

| Dependency
| `eventuate-tram-spring-consumer-jdbc` (or indirectly via `eventuate-tram-spring-jdbc-<message-broker>`)
| `eventuate-tram-spring-consumer-jdbc` (or indirectly via `eventuate-tram-spring-jdbc-<message-spring-jdbc-<message-broker>`)
| -

| `@Configuration`
| Either auto-configuration or `@Import` `TramConsumerJdbcAutoConfiguration`
| `@Import` `TransactionalNoopDuplicateMessageDetectorConfiguration`
| `@Import` `NoopDuplicateMessageDetector`

|===

[source,groovy]
----
dependency {
  compile "io.eventuate.tram.core:eventuate-tram-spring-consumer-jdbc:$eventuateTramVersion"
}
----

===== Micronaut


[cols="4*a"]
|===

|
| `SqlTableBasedDuplicateMessageDetector`
| `TransactionalNoopDuplicateMessageDetector`
| `NoopDuplicateMessageDetector`

| Dependency
| `eventuate-tram-micronaut-consumer-jdbc` directly or indirectly via `eventuate-tram-micronaut-jdbc-<message-broker>`
| `eventuate-tram-micronaut-consumer-jdbc` directly or indirectly via `eventuate-tram-micronaut-jdbc-<message-micronaut-jdbc-<message-broker>`
| -

| Configuration
| do not set `transactional.noop.duplicate.message.detector.factory.enabled`
| set `transactional.noop.duplicate.message.detector.factory.enabled`
| The default if no other `DuplicateMessageDetector` `@Bean` is defined

|===

[source,groovy]
----
dependency {
  compile "io.eventuate.tram.core:eventuate-tram-micronaut-consumer-jdbc:$eventuateTramVersion"
}
----

==== Optimistic locking

If your application uses a `DuplicateMessageDetector` that manages transactions and your message handler uses optimistic locking then you must configure Eventuate Tram to retry the transaction when an optimistic locking failure occurs.

==== Spring

To configure retries, you must:

* Add `eventuate-tram-optimistic-locking` as a dependency
* `@Import` `OptimisticLockingDecoratorConfiguration`

This configures an `OptimisticLockingDecorator` `@Bean`, which is a `MessageHandlerDecorator` that retries when an `OptimisticLockingFailureException` is thrown.

==== Micronaut

Not yet implemented: https://github.com/eventuate-tram/eventuate-tram-core/issues/96[Issue #46]

=== Transactional domain events

The domain event package builds on the transaction messaging APIs.

==== Publishing domain events

Publish domain events using the `DomainEventPublisher` interface:

===== Spring

[source,java]
----
public abstract class AbstractTramEventTest {

  @Autowired
  private DomainEventPublisher domainEventPublisher;

  @Test
  public void shouldReceiveEvent() throws InterruptedException {
    long uniqueId = config.getUniqueId();
    String accountId = ...;

    DomainEvent domainEvent = new AccountDebited(...);

    domainEventPublisher.publish("Account", accountId, Collections.singletonList(domainEvent));
----

To publish events you need to `@Import` the `TramEventsPublisherConfiguration` `@Configuration` class:

[source,java]
----
@Configuration
@Import(TramEventsPublisherConfiguration.class)
public class AbstractTramEventTestConfiguration {
...
----


See this example of https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/events/AbstractTramEventTest.java[transaction events].

===== Micronaut

[source,java]
----
public abstract class AbstractTramEventTest {

  @Inject
  private DomainEventPublisher domainEventPublisher;

  @Test
  public void shouldReceiveEvent() throws InterruptedException {
    long uniqueId = config.getUniqueId();
    String accountId = ...;

    DomainEvent domainEvent = new AccountDebited(...);

    domainEventPublisher.publish("Account", accountId, Collections.singletonList(domainEvent));
----

To publish events you need to have `TramEventsPublisherFactory` class in your classpath (see <<dependency-configuration-section, dependency configuration section>>):

```groovy
dependencies {
    compile "io.eventuate.tram.core:eventuate-tram-micronaut-events:$eventuateTramVersion"
}
```


See this example of https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/events/AbstractTramEventTest.java[transaction events].

==== Consuming domain events

First, define `DomainEventHandlers`:

[source,java]
----
public class TramEventTestEventConsumer {

  public DomainEventHandlers domainEventHandlers() {
    return DomainEventHandlersBuilder
            .forAggregateType("Account")
            .onEvent(AccountDebited.class, this::handleAccountDebited)
            .build();
  }

  public void handleAccountDebited(DomainEventEnvelope<AccountDebited> event) {
    ...
  }

}
----

Second, configure a `DomainEventDispatcher`:

===== Spring

[source,java]
----
@Configuration
public class AbstractTramEventTestConfiguration {

  @Bean
  public DomainEventDispatcher domainEventDispatcher(DomainEventDispatcherFactory domainEventDispatcherFactory,,
                                                     AbstractTramEventTestConfig config,
                                                     TramEventTestEventConsumer target) {
    return domainEventDispatcherFactory.make("eventDispatcherId",
            target.domainEventHandlers());
  }

  @Bean
  public TramEventTestEventConsumer tramEventTestTarget(AbstractTramEventTestConfig config) {
    return new TramEventTestEventConsumer();
  }
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/events/AbstractTramEventTest.java[transaction events].

===== Micronaut

[source,java]
----
@Factory
public class AbstractTramEventTestFactory {

  @Context
  public DomainEventDispatcher domainEventDispatcher(AbstractTramEventTestConfig config,
                                                     TramEventTestEventConsumer target,
                                                     DomainEventDispatcherFactory domainEventDispatcherFactory) {
    return domainEventDispatcherFactory.make("eventDispatcherId" + config.getUniqueId(), target.domainEventHandlers());
  }

  @Singleton
  public TramEventTestEventConsumer tramEventTestTarget(AbstractTramEventTestConfig config) {
    return new TramEventTestEventConsumer(config.getAggregateType());
  }
}
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/events/AbstractTramEventTestFactory.java[transaction events].


=== Transactional commands

Transactional commands are implemented using transactional messaging.

==== Sending commands

Send a command using a `CommandProducer`:

===== Spring

[source,java]
----
public abstract class AbstractTramCommandTest {

  @Autowired
  private CommandProducer commandProducer;

  @Test
  public void shouldInvokeCommand() throws InterruptedException {

    String commandId = commandProducer.send("CustomerCommandChannel",
            new DoSomethingCommand(),
            "ReplyToChannel",
            Collections.emptyMap());

----

You also need to `@Import` the `TramCommandProducerConfiguration` `@Configuration` class:

[source,java]
----
@Configuration
@Import(TramCommandProducerConfiguration.class)
public class AbstractTramCommandTestConfiguration {

----

To handle a reply message, simply subscribe to the `ReplyChannel`.

[source,java]
----
messageConsumer.subscribe(subscriberId, "ReplyToChannel", this::handleMessage);
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/commands/AbstractTramCommandTest.java[transactional commands].

===== Micronaut

[source,java]
----
public abstract class AbstractTramCommandTest {

  @Inject
  private CommandProducer commandProducer;

  @Test
  public void shouldInvokeCommand() throws InterruptedException {

    String commandId = commandProducer.send("CustomerCommandChannel",
            new DoSomethingCommand(),
            "ReplyToChannel",
            Collections.emptyMap());

----

You also need to have the `TramCommandProducerFactory` in your classpath (see <<dependency-configuration-section, dependency configuration section>>):

```groovy
dependencies {
    compile "io.eventuate.tram.core:eventuate-tram-micronaut-commands:$eventuateTramVersion"
}
```

To handle a reply message, simply subscribe to the `ReplyChannel`.

[source,java]
----
messageConsumer.subscribe(subscriberId, "ReplyToChannel", this::handleMessage);
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/commands/AbstractTramCommandTest.java[transactional commands].

==== Handling commands

First, define `CommandHandlers`:

[source,java]
----
public class TramCommandTestCommandHandler {

  public Message doSomething(CommandMessage<DoSomethingCommand> cm, PathVariables pvs) {
    ...
    return withSuccess();
  }

  public CommandHandlers getCommandHandlers() {
    return CommandHandlersBuilder
            .fromChannel("CustomerCommandChannel")
            .onMessage(DoSomethingCommand.class, this::doSomething)
            .build();

  }
----

Second, define a `CommandDispatcher`:

===== Spring

[source,java]
----
@Configuration
public class AbstractTramCommandTestConfiguration {

  @Bean
  public CommandDispatcher commandDispatcher(CommandDispatcherFactory commandDispatcherFactory,
                                             AbstractTramCommandTestConfig config,
                                             AbstractTramCommandTestCommandHandler target) {
  return commandDispatcherFactory.make("customerServiceCommandDispatcher", target.getCommandHandlers());
}

@Bean
public TramCommandTestCommandHandler abstractTramCommandTestTarget(AbstractTramCommandTestConfig config) {
  return new TramCommandTestCommandHandler(config.getCommandChannel());
}
----

===== Micronaut

[source,java]
----
@Factory
public class AbstractTramCommandTestFactory {

  @Singleton
  public TramCommandTestCommandHandler abstractTramCommandTestTarget(AbstractTramCommandTestConfig config) {
    return new TramCommandTestCommandHandler(config.getCommandChannel());
  }

  @Singleton
  public CommandDispatcher commandDispatcher(CommandDispatcherFactory commandDispatcherFactory,
                                             AbstractTramCommandTestConfig config,
                                             TramCommandTestCommandHandler target) {
    return commandDispatcherFactory.make(config.getCommandDispatcheId(), target.getCommandHandlers());
  }
}
----

See this example of https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-common/src/main/java/io/eventuate/tram/examples/basic/commands/AbstractTramCommandTest.java[transactional commands].


=== Configuring the transport

===== Spring

You also need to configure the transport mechanism, specifically the message broker.
You do this importing one of the `TramJdbc<MessageBroker>Configuration` classes:

* `TramJdbcKafkaConfiguration`
* `TramJdbcActiveMQConfiguration`
* `TramJdbcRabbitMQConfiguration`
* `TramJdbcRedisConfiguration`
* `TramInMemoryConfiguration` - in-memory JDBC and messaging

For example, if you want to use JDBC/Apache Kafka then `@Import` `TramJdbcKafkaConfiguration`:

[source,java]
----
@Configuration
@EnableAutoConfiguration
@Import({TramJdbcKafkaConfiguration.class})
public class JdbcKafkaTramMessageTestConfiguration {
}
----

The `TramJdbc<MessageBroker>Configuration` `@Configuration` classes configure both a producer and a consumer.
If you have a service that is either only a producer or only a consumer you can use a more specific  `@Configuration` class.

To configure a producer, `@Import` the `TramMessageProducerJdbcConfiguration` @Configuration class.

To consumer a consumer, `@Import` one of the `EventuateTram<MessageBroker>MessageConsumerConfiguration` @Configuration classes:

* `EventuateTramKafkaMessageConsumerConfiguration`
* `EventuateTramActiveMQMessageConsumerConfiguration`
* `EventuateTramRabbitMQMessageConsumerConfiguration`
* `EventuateTramRedisMessageConsumerConfiguration`

For example, see the FTGO application's https://github.com/microservices-patterns/ftgo-application/blob/master/ftgo-order-history-service/src/main/java/net/chrisrichardson/ftgo/cqrs/orderhistory/main/OrderHistoryServiceMain.java[`Order History Service`], which is a consumer-only service.

===== Micronaut

For now, the Micronaut version of Eventuate only supports Apache Kafka as the transport mechanism.

You don't need to create additional configuration, you only need to setup dependencies (see <<dependency-configuration-section, dependency configuration section>>):

=== Configuration properties

There are various configuration properties that need to be set for each transport.

Since JDBC is used, you must set the usual properties, such as:

===== Spring

----
spring.datasource.url=jdbc:mysql://${DOCKER_HOST_IP}/eventuate
spring.datasource.username=mysqluser
spring.datasource.password=mysqlpw
spring.datasource.driver.class.name=com.mysql.jdbc.driver
----

===== Micronaut

----
datasources:
  default:
    url: dbc:mysql://${DOCKER_HOST_IP}/eventuate
    driverClassName: com.mysql.jdbc.driver
    username: mysqluser
    password: mysqlpw
----


In addition, you need to define message broker-specific properties.

===== Spring

[cols="25%, 75%", options="header"]
|===
| Message Broker
| Properties

| Apache Kafka
a|
----
eventuatelocal.kafka.bootstrap.servers=${DOCKER_HOST_IP}:9092
eventuatelocal.zookeeper.connection.string=${DOCKER_HOST_IP}:2181
----

| Apache ActiveMQ
a|
----
activemq.url=...
----

| RabbitMQ
a|
----
rabbitmq.url=...
eventuate.rabbitmq.partition.count=...
----

| Redis
a|
----
eventuate.redis.servers=...
eventuate.redis.partitions=...
----

|===

See spring https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/eventuate-tram-examples-jdbc-kafka/src/test/resources/application.properties[application.properties]

===== Micronaut

[cols="25%, 75%", options="header"]
|===
| Message Broker
| Properties

| Apache Kafka
a|
----
eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP}:2181
----
|===


See micronaut https://github.com/eventuate-tram/eventuate-tram-core-micronaut-examples-basic/blob/master/eventuate-tram-examples-jdbc-kafka/src/test/resources/application.yml[application.yml]

==== In-memory transport

===== Spring

If you want to use in-memory transport `@Import` `TramInMemoryConfiguration`:

[source,java]
----
@Configuration
@EnableAutoConfiguration
@Import({TramInMemoryConfiguration.class})
public class TramInMemoryConfiguration {
}
----

===== Micronaut

If you want to use in-memory transport include eventuate-tram-micronaut-in-memory dependency:

```groovy
dependencies {
    compile "io.eventuate.tram.core:eventuate-tram-micronaut-in-memory:$eventuateTramVersion"
}
```

=== Running the CDC service

In addition to a database and message broker, you will need to run the link:./cdc-configuration.html[Eventuate Tram CDC] service.
It reads events inserted into the database and publishes them to the message broker.
It is written using Spring Boot.
The easiest way to run this service during development is to use Docker Compose.

The https://github.com/eventuate-tram/eventuate-tram-core-examples-basic[Eventuate Tram Code Basic examples] project has an example https://github.com/eventuate-tram/eventuate-tram-core-examples-basic/blob/master/docker-compose.yml[docker-compose.yml file].

[source,yaml]
----
cdcservice:
  image: eventuateio/eventuate-tram-cdc-mysql-service:0.4.0.RELEASE
  ports:
    - "8099:8080"
  depends_on:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
    EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog
    EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
    EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
----

For more information, please see link:./cdc-configuration.html[Eventuate Tram CDC]
